---
version: 2.1

executors:
  build-executor:
    docker:
      - image: quay.io/labmonkeys/cimg-base:2023.06-22.04.b50

commands:
  make-image:
    description: "Build OCI image and publish from main branch"
    parameters:
      workdir:
        default: "~/project"
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build OCI image and publish from main branch
          command: |
            cd << parameters.workdir >> && pwd
            if git show --name-only --format='' . | grep ""; then
              echo "Changes detected trigger build"
              if [[ "${CIRCLE_BRANCH}" == "main" ]]; then make publish BUILD_VERSION_SUFFIX=".b${CIRCLE_BUILD_NUM}"; else make oci; fi
            else
              echo "No changes in directory << parameters.workdir >> detected, skip build."
            fi

workflows:
  version: 2

  build:
    jobs:
      - cimg:
          context: "Publishing"
      - vmbuilder:
          context: "Publishing"

jobs:
  cimg:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./cimg"

  vmbuilder:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./vmbuilder"
